{
 "title": "FISCO-BCOS区块链监控视图",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  max(block_height) AS \"block_height\"\nFROM block_task_pool where sync_status=2 \n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(tx_count)\nFROM block_detail_info\n"
    }
   ]
  },
  {
   "title": "区块增长高度趋势",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  block_timestamp AS \"time\",\n  block_height\nFROM block_detail_info\nWHERE\n  $__timeFilter(block_timestamp)\nORDER BY block_timestamp"
    }
   ]
  },
  {
   "title": "区块实时下载数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(depot_updatetime) DIV 1 * 1 AS \"time\",\n  count(pk_id) as value\nFROM block_task_pool where sync_status=2 \nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "区块下载情况",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT block_height, certainty, sync_status, handle_item, depot_updatetime from block_task_pool;"
    }
   ]
  },
  {
   "title": "区块交易详情",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT block_height, contract_name, method_name, block_timestamp from block_tx_detail_info order by block_height;"
    }
   ]
  },
  {
   "title": "外部所有账户信息",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT block_height, contract_name, contract_address, block_timestamp from account_info;"
    }
   ]
  },
  {
   "title": "Learn More",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "content": "\n# 本页面来源于WEBASE-BEE\n\n\n点击详情获得更多支持: [WeBankFinTech/WeBASE-Collect-Bee](https://github.com/WeBankFinTech/WeBASE-Collect-Bee/tree/master)\n\n\n# 本应用支持FISCO-BCOS公众联盟链\n\n点击详情获得更多支持: [FISCO-BCOS](https://www.fisco.com.cn/)\n\n\n",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "BAC003URI",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "select * from b_a_c003_u_r_i order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC003ApprovalForAll",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "select * from b_a_c003_approval_for_all order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC003TransferBatch",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "select * from b_a_c003_transfer_batch order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC003TransferSingle",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "select * from b_a_c003_transfer_single order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001IssuerRemoved",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_issuer_removed order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001IssuerAdded",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_issuer_added order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001SuspenderRemoved",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_suspender_removed order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001SuspenderAdded",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_suspender_added order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001UnSuspended",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_un_suspended order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001Suspended",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_suspended order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001Approval",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_approval order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001Send",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_send order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002IssuerRemoved",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_issuer_removed order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002IssuerAdded",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_issuer_added order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002SuspenderRemoved",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 144 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_suspender_removed order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002SuspenderAdded",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 152 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_suspender_added order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002UnSuspended",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 160 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_un_suspended order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002Suspended",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 168 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_suspended order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002ApprovalForAll",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 176 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_approval_for_all order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002Approval",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 184 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_approval order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002Send",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 192 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_send order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC003SafeBatchTransferFrom",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 200 },
   "targets": [
    {
     "rawSql": "select * from b_a_c003_safe_batch_transfer_from order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC003SetURI",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 208 },
   "targets": [
    {
     "rawSql": "select * from b_a_c003_set_u_r_i order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC003SetApprovalForAll",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 216 },
   "targets": [
    {
     "rawSql": "select * from b_a_c003_set_approval_for_all order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC003Increase",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 224 },
   "targets": [
    {
     "rawSql": "select * from b_a_c003_increase order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC003Destroy",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 232 },
   "targets": [
    {
     "rawSql": "select * from b_a_c003_destroy order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC003Create",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 240 },
   "targets": [
    {
     "rawSql": "select * from b_a_c003_create order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC003SafeTransferFrom",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 248 },
   "targets": [
    {
     "rawSql": "select * from b_a_c003_safe_transfer_from order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001Approve",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 256 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_approve order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001AddIssuer",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 264 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_add_issuer order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001IncreaseAllowance",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 272 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_increase_allowance order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001SafeSendFrom",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 280 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_safe_send_from order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001AddSuspender",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 288 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_add_suspender order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001SafeBatchSend",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 296 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_safe_batch_send order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001DestroyFrom",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 304 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_destroy_from order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001SafeSend",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 312 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_safe_send order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001Destroy",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 320 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_destroy order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001DecreaseAllowance",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 328 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_decrease_allowance order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001SendFrom",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 336 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_send_from order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001Issue",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 344 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_issue order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001Send",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 352 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_send order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC001BAC001",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 360 },
   "targets": [
    {
     "rawSql": "select * from b_a_c001_b_a_c001 order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002SafeSendFrom",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 368 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_safe_send_from order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002Destroy",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 376 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_destroy order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002Approve",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 384 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_approve order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002AddIssuer",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 392 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_add_issuer order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002AddSuspender",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 400 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_add_suspender order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002SetApprovalForAll",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 408 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_set_approval_for_all order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002IssueWithAssetURI",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 416 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_issue_with_asset_u_r_i order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002SendFrom",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 424 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_send_from order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002SafeBatchSendFrom",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 432 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_safe_batch_send_from order by depot_updatetime;"
    }
   ]
  },
  {
   "title": "BAC002BAC002",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 440 },
   "targets": [
    {
     "rawSql": "select * from b_a_c002_b_a_c002 order by depot_updatetime;"
    }
   ]
  }
 ]
}